#!/usr/bin/env python3

from sys import argv
from subprocess import call

fname = '/dev/stdin'
if len(argv) >= 2:
    fname = argv[1]

if fname == '-h' or fname == '--help':
    print(f'Usage: {argv[0]} [FILENAME]')
    exit(0)

call(['sleep', '5'])
with open(fname, 'r') as f:
    for l in f:
        call(['xdotool', 'type', '--delay', '60', l])
        #call(['xdotool', 'key', 'Return'])
